spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: P@ssw0rd
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.r2dbc.core: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.h2: DEBUG
    io.r2dbc.spi: DEBUG
    org.springframework.r2dbc.connection: DEBUG
    web: DEBUG

user:
  email:
    pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
    message: "Invalid email format"
    exist:
      message: "Email already exists"
  password:
    pattern: ^(?=.*[A-Z])(?=.*\d)[A-Za-z\d]{8,12}$
    message: "Password must be 8-12 characters long, contain at least one uppercase letter and one digit"


